apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aiops.aiops.geektime.com
spec:
  group: aiops.geektime.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                openai_api_key:
                  type: string
                  description: openai_api_key
                openai_api_base:
                  type: string
                  description: openai_api_base
            status:
              type: object
  scope: Namespaced
  names:
    plural: aiops
    singular: aiops
    kind: AIOps
    shortNames:
      - aio
